/**
 * Standardized error codes for API responses.
 */
export enum ErrorCode {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
  EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED',
  PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND',
  PROFILE_ALREADY_EXISTS = 'PROFILE_ALREADY_EXISTS',
  INVALID_PHONE_NUMBER = 'INVALID_PHONE_NUMBER',
  INVALID_ADDRESS = 'INVALID_ADDRESS',
  INVALID_GEOJSON = 'INVALID_GEOJSON',
  SERVICE_OFFERING_NOT_FOUND = 'SERVICE_OFFERING_NOT_FOUND',
  AVAILABILITY_NOT_FOUND = 'AVAILABILITY_NOT_FOUND',
  FAVORITE_ALREADY_EXISTS = 'FAVORITE_ALREADY_EXISTS',
  FAVORITE_NOT_FOUND = 'FAVORITE_NOT_FOUND',
  CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',
  CATEGORY_ALREADY_EXISTS = 'CATEGORY_ALREADY_EXISTS',
  QUESTION_NOT_FOUND = 'QUESTION_NOT_FOUND',
  CONTENT_NOT_FOUND = 'CONTENT_NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
